name: camvote
description: Secure Digital Electoral System for Cameroon
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.5.1

  # HTTP & Networking
  dio: ^5.4.0

  # Local Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Secure Storage
  flutter_secure_storage: ^9.0.0

  # Biometrics
  local_auth: ^2.1.8
  local_auth_android: ^1.0.38
  local_auth_darwin: ^1.3.1

  # QR Code
  qr_flutter: ^4.1.0


  # Image Handling
  image_picker: ^1.0.7
  permission_handler: ^11.2.0

  # Location
  geolocator: ^11.0.0
  google_maps_flutter: ^2.5.3

  # Utilities
  intl: ^0.19.0
  uuid: ^4.3.3
  crypto: ^3.0.3

  # UI
  cupertino_icons: ^1.0.8
  mobile_scanner: ^7.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.8
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true